apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards

dashboards:
  - name: 'SVG Display Dashboard'
    folder: 'General'
    type: file
    options:
      path: /var/lib/grafana/dashboards/svg-display.json

security:
  adminUser: admin
  adminPassword: admin

server:
  http_port: 3000
  domain: localhost
  root_url: %(protocol)s://%(domain)s:%(http_port)s/
  router_logging: true

analytics:
  reporting_enabled: false
  check_for_updates: true

auth:
  disable_login_form: false

users:
  allow_sign_up: false
  auto_assign_org: true
  auto_assign_org_role: Viewer

plugins:
  - name: marcusolsson-svg-panel
    version: 1.0.0
    enabled: true
